# Версия интерпретатора питона (указываем и забываем)
version: "3.9"

# Описание всех серверов MySQL
services:
    # Описание master-server
    mysql-master:
        # Образ MySQL СУБД, скачиваемый из Интернета (официальный образ)
        image: 'mysql:8.0'
        # MySql не будет плевать в лог докер-контейнера не значительные уведомления
        cap_add:
            - SYS_NICE
        # Имя докер-контейнера (имя запущенного докер-образа, также имя хоста в DNS)
        container_name: mysql-master
        # Передача файлов из местной ОС внутрь контейнера
        volumes:
            - ./master.cnf:/etc/mysql/my.cnf
            - ./master.sql:/docker-entrypoint-initdb.d/start.sql
        # Указываем переменную окружения внутри контейнера
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        # Пробрасываем порт с хостовой машины внутрь докера для возможности подключения к СУБД снаружи
        ports:
          - '3306:3306'
    # Описание Slave-server
    mysql-slave:
        image: 'mysql:8.0'
        cap_add:
            - SYS_NICE
        container_name: mysql-slave
        volumes:
            - ./slave.cnf:/etc/mysql/my.cnf
            - ./slave.sql:/docker-entrypoint-initdb.d/start.sql
        # Указываем, что slave запускается только после успешного запуска master
        depends_on:
            - mysql-master
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        ports:
          - '3307:3306'
    # Описание Slave-server
    mysql-consol:
        image: 'mysql:8.0'
        cap_add:
            - SYS_NICE
        container_name: mysql-consol
        volumes:
            - ./consol.cnf:/etc/mysql/my.cnf
            - ./consol.sql:/docker-entrypoint-initdb.d/start.sql
        # Указываем, что slave запускается только после успешного запуска master
        depends_on:
            - mysql-master
            - mysql-slave
        environment:
            MYSQL_ROOT_PASSWORD: "password"
        ports:
          - '3308:3306'
